apiVersion: v1
kind: Service
metadata:
  name: {{ include "sprint-petclinic-reactjs-frontend.fullname" . }}
  labels:
{{ include "sprint-petclinic-reactjs-frontend.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4444
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sprint-petclinic-reactjs-frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
